# Generated by Django 4.2.4 on 2023-10-05 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addr',
            name='address',
            field=models.CharField(default='', max_length=100, verbose_name='详细地址'),
        ),
        migrations.AlterField(
            model_name='addr',
            name='county',
            field=models.CharField(default='', max_length=20, verbose_name='区县'),
        ),
    ]
