# Generated by Django 4.2.4 on 2024-01-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_addr_address_alter_addr_county'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addr',
            options={'verbose_name': '收货地址表', 'verbose_name_plural': '收货地址表'},
        ),
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': '地区表', 'verbose_name_plural': '地区表'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户表', 'verbose_name_plural': '用户表'},
        ),
        migrations.AlterModelOptions(
            name='verifcode',
            options={'verbose_name': '手机验证码表', 'verbose_name_plural': '手机验证码表'},
        ),
        migrations.AlterField(
            model_name='area',
            name='pid',
            field=models.IntegerField(verbose_name='上级id'),
        ),
    ]
