# Generated by Django 4.2.4 on 2024-01-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goodsgroup',
            options={'verbose_name': '商品分类表', 'verbose_name_plural': '商品分类表'},
        ),
        migrations.AlterField(
            model_name='goodsgroup',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='分类图标'),
        ),
    ]
