# Generated by Django 4.2.4 on 2024-03-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_is_checked_alter_cart_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_id', models.CharField(help_text='购物车ID', max_length=100, unique=True, verbose_name='购物车ID')),
                ('battery_level', models.IntegerField(help_text='电池电量', verbose_name='电池电量')),
                ('following_mode', models.BooleanField(help_text='运行模式', verbose_name='运行模式')),
                ('charging', models.BooleanField(help_text='充电状态', verbose_name='充电状态')),
                ('location', models.CharField(help_text='位置', max_length=255, verbose_name='位置')),
                ('product_recognition_active', models.BooleanField(help_text='工作状态', verbose_name='工作状态')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '购物车实时状态',
                'verbose_name_plural': '购物车实时状态',
                'db_table': 'cart_status',
            },
        ),
    ]
